In [2]:
import numpy as np

# PRINT

In [5]:
x = 3
print('Integer: %01d %02d %03d %04d %05d' % (x,x,x,x,x))

x = 123.456
print('Float: %.0f %.1f %.2f %1.2f %2.2f' % (x,x,x,x,x))

x = 'Hello, World !!!'
print('String: [%s], [%3s], [%20s]' % (x,x,x))

Integer: 3 03 003 0003 00003
Float: 123 123.5 123.46 123.46 123.46
String: [Hello, World !!!], [Hello, World !!!], [    Hello, World !!!]


# FOR + IF/ELIF/ELSE

In [11]:
deeplearning_methods = ['ANN', 'MLP', 'CNN', 'RNN', 'DAE']

for alg in deeplearning_methods:
    if alg in ['ANN', 'MLP', 'CNN']:
        print('%s is feed-forward network.' % alg)
    elif alg in ['RNN']:
        print('%s is recurrent network.' % alg)
    else:
        print('%s is an unsupervised methods.' % alg)
        
#More advanced
print('\n FOR loop with index.')
for i, alg in zip(range(len(deeplearning_methods)), deeplearning_methods):
    if alg in ['ANN', 'MLP', 'CNN']:
        print('[%d/%d] %s is a feed_forward network.' % (i+1, len(deeplearning_methods), alg))
    elif alg in ['RNN']:
        print('[%d/%d] %s is a recurrent network.' % (i+1, len(deeplearning_methods), alg))
    else:
        print('[%d/%d] %s is an unsupervised method.' % (i+1, len(deeplearning_methods), alg))

ANN is feed-forward network.
MLP is feed-forward network.
CNN is feed-forward network.
RNN is recurrent network.
DAE is an unsupervised methods.

 FOR loop with index.
[1/5] ANN is a feed_forward network.
[2/5] MLP is a feed_forward network.
[3/5] CNN is a feed_forward network.
[4/5] RNN is a recurrent network.
[5/5] DAE is an unsupervised method.


# Function in Python

In [14]:
#Function definition
def sum(a,b):
    return a+b

x = 10.
y = 20.
print('%.1f + %.1f = %.1f' % (x, y, sum(x,y)))

10.0 + 20.0 = 30.0


# String operation

In [30]:
head = 'Deep Learning'
body = 'very '
tail = 'HARD!!!!'
print(head, 'is', body, tail)
#Repeat words
print(head, 'is', body*5, tail)
print(head + ' is ' + body*5 + tail)

#It is used in this way
print('\n' + '='*50)
print(' '*15 + 'It is used in this way')
print('='*50, '\n')

#Indexing characters in the string
x = 'Hello, World!!!'
for i in range(len(x)):
    print('Index: [%02d/%02d] Char: %s' % (i+1, len(x), x[i]))

Deep Learning is very  HARD!!!!
Deep Learning is very very very very very  HARD!!!!
Deep Learning is very very very very very HARD!!!!

               It is used in this way

Index: [01/15] Char: H
Index: [02/15] Char: e
Index: [03/15] Char: l
Index: [04/15] Char: l
Index: [05/15] Char: o
Index: [06/15] Char: ,
Index: [07/15] Char:  
Index: [08/15] Char: W
Index: [09/15] Char: o
Index: [10/15] Char: r
Index: [11/15] Char: l
Index: [12/15] Char: d
Index: [13/15] Char: !
Index: [14/15] Char: !
Index: [15/15] Char: !


In [35]:
#More indexing
print('')
idx = 2
print('(%d)th char is %s' % (idx, x[idx]))
idxfr = 0
idxto = 8
print('String from %d to %d is [%s]' % (idxfr, idxto, x[idxfr:idxto]))

idxfr = 4
print('String from %d to END is [%s]' % (idxfr, x[idxfr:]))

x = '20180607cloudy'
year = x[:4]
day = x[4:8]
weather = x[8:]
print('[%s] -> [%s] + [%s] + [%s]' % (x, year, day, weather))


(2)th char is l
String from 0 to 8 is [Hello, W]
String from 4 to END is [o, World!!!]
[20180607cloudy] -> [2018] + [0607] + [cloudy]


# LIST

In [56]:
a = []
b = [1,2,3]
c = ['Hello', ',', 'World!!']
d = [1,2,3,'x','y','z']
x = []
print(type(x), x)
x.append('a')
print(type(x), x)
x.append(123)
print(type(x), x)
x.append(['a', 'b'])
print(type(x), x)
print('\nLength of x is %d' % (len(x)))
for i in range(len(x)):
    print('[%02d/%02d] %s' % (i+1, len(x), x[i]))

print('')
z = []
z.append(1)
print(type(z), z)
z.append(2)
print(type(z), z)
z.append(3)
z.append('Hello')
print(type(z), z)
for i in range(len(z)):
    print(z[i])

<class 'list'> []
<class 'list'> ['a']
<class 'list'> ['a', 123]
<class 'list'> ['a', 123, ['a', 'b']]

Length of x is 3
[01/03] a
[02/03] 123
[03/03] ['a', 'b']

<class 'list'> [1]
<class 'list'> [1, 2]
<class 'list'> [1, 2, 3, 'Hello']
1
2
3
Hello


# Dictionary

In [78]:
dic = dict()
dic['name'] = 'Hong'
dic['age'] = 26
dic['job'] = 'Student'
print(dic)
print(dic['name'])

{'age': 26, 'name': 'Hong', 'job': 'Student'}
Hong


## Iterate through a dictionary - dic.items()

In [77]:
keylist = []
valuelist = []
for key, value in dic.items():
    keylist.append(key)
    valuelist.append(value)
print('Key list is: ', keylist)
print('Value list is: ', valuelist)

Key list is:  ['age', 'name', 'job']
Value list is:  [26, 'Hong', 'Student']


# Class

In [82]:
class Greeter:
    
    #Constructor
    def __init__(self, name):
        self.name = name #Create an instance variable
    
    #Instance method
    def greet(self, loud=False):
        if loud:
            print('Hello, %s!!' % self.name.upper())
        else:
            print('Hello, %s!!' % self.name)

g1 = Greeter('Hong') #Construct an instance of Greeter class
g1.greet()           #Call an instance method
g1.greet(loud=True)  #Call another instance method with variable
print('')
g2 = Greeter('Nguyen') #Construct another instance of Greeter class
g2.greet()
g2.greet(loud=True)

Hello, Hong!!
Hello, HONG!!

Hello, Nguyen!!
Hello, NGUYEN!!


# Numpy

In [95]:
def print_np(x):
    print('Type is %s' % type(x))
    print('Shape is ', x.shape)
    print('Values are: \n%s' % (x))

## Rank 1 Array

In [96]:
x = np.array([1,2,3]) #Rank 1 array
print_np(x)
print('')
x[0] = 5
print_np(x)

Type is <class 'numpy.ndarray'>
Shape is  (3,)
Values are: 
[1 2 3]

Type is <class 'numpy.ndarray'>
Shape is  (3,)
Values are: 
[5 2 3]


## Rank 2 Array

In [99]:
y = np.array([ [1,2,3],[4,5,6] ]) #Rank 2 array
print_np(y)
print('')
y[1][2] = 20 #Change the 6 value
print_np(y)

Type is <class 'numpy.ndarray'>
Shape is  (2, 3)
Values are: 
[[1 2 3]
 [4 5 6]]

Type is <class 'numpy.ndarray'>
Shape is  (2, 3)
Values are: 
[[ 1  2  3]
 [ 4  5 20]]


## Zeros matrix

In [105]:
zeros = np.zeros((5,5))
print_np(zeros)
print('')
zeros = np.zeros_like(y) #New Zeros matrix has the same shape as y 
print_np(zeros)

Type is <class 'numpy.ndarray'>
Shape is  (5, 5)
Values are: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Type is <class 'numpy.ndarray'>
Shape is  (2, 3)
Values are: 
[[0 0 0]
 [0 0 0]]


## Ones matrix

In [108]:
ones = np.ones((5,5))
print_np(ones)
print('')
ones = np.ones_like(y) #New Ones matrix has the same shape as y
print_np(ones)

Type is <class 'numpy.ndarray'>
Shape is  (5, 5)
Values are: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Type is <class 'numpy.ndarray'>
Shape is  (2, 3)
Values are: 
[[1 1 1]
 [1 1 1]]


## Identity matrix

In [115]:
eye = np.eye(5,5)
print_np(eye)
print('')
eye1 = np.eye(5, 8)
print_np(eye1)

Type is <class 'numpy.ndarray'>
Shape is  (5, 5)
Values are: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Type is <class 'numpy.ndarray'>
Shape is  (5, 8)
Values are: 
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


## Random

In [153]:
random_rand = np.random.rand(3,2) #np.random.rand just the postive value (0 -> 1)
print_np(random_rand)
print('')
random_randint = np.random.randint(10, size=(3,5)) #np.random.randint random int values (0 -> high)
print_np(random_randint)

Type is <class 'numpy.ndarray'>
Shape is  (3, 2)
Values are: 
[[0.50831287 0.04935922]
 [0.59138353 0.93317763]
 [0.09340331 0.21828339]]

Type is <class 'numpy.ndarray'>
Shape is  (3, 5)
Values are: 
[[7 4 8 4 5]
 [2 9 8 1 8]
 [3 2 7 1 9]]


## Random (uniform)

In [120]:
rand_uniform = np.random.uniform(low=0,high=100,size=[5,5]).astype('int32')
print_np(rand_uniform)

Type is <class 'numpy.ndarray'>
Shape is  (5, 5)
Values are: 
[[27  1 41 20 98]
 [32 77 40 20  1]
 [63 22 45 69 81]
 [43 77 34 20 81]
 [13 25  0 65 13]]


## Random (gaussian)

In [154]:
rand_gaussian = np.random.randn(5,5) #np.random.randn include the negative value (-1 -> 3)
print_np(random_randn)

Type is <class 'numpy.ndarray'>
Shape is  (3, 2)
Values are: 
[[ 0.75441265 -0.33507649]
 [-0.96904024  0.95040166]
 [-0.23646102  0.09707003]]


## Array Indexing

In [166]:
#Create a rank 2 array
a = np.array(np.random.randint(20, size=(5,8)))
print_np(a)

print('')
#Use slicing to pull out the subarray consisting of the first 2 rows
b = a[:3, :3]
print_np(b)

print('')
#Take the specific value after slice
c = a[:3, :3][1][0]
print_np(c)

Type is <class 'numpy.ndarray'>
Shape is  (5, 8)
Values are: 
[[11  2 17 12 19  8  3 15]
 [ 4  1  7  1  6  0 13  6]
 [10  7 15  4 18  6 17 13]
 [ 9  9 10 10 17  5  6  5]
 [ 9  3  3 16 14 14 19 13]]

Type is <class 'numpy.ndarray'>
Shape is  (3, 3)
Values are: 
[[11  2 17]
 [ 4  1  7]
 [10  7 15]]

Type is <class 'numpy.int32'>
Shape is  ()
Values are: 
4


## Get Row

In [176]:
a = np.array(np.random.randint(20, size=(5,8)))
print_np(a)
print('')

row2_rank1 = a[1, :]     #Rank 1 view of the second row of a
row2_rank2 = a[1:2, :]   #Rank 2 view of the second row of a
row2_r3 = a[[1], :]      #Rank 2 view of the second row of a (another method)
print('Row 2 of rank 1 is: ', row2_rank1)
print('Row 2 of rank 2 is: ', row2_rank2)
print('Row 2 of rank 2 (another method) is:', row2_r3)

Type is <class 'numpy.ndarray'>
Shape is  (5, 8)
Values are: 
[[10  7  2 14 12 15 12  4]
 [18 19 14  3 19  0 14 16]
 [11  6 18 17 16 19  4 19]
 [ 7  1  1  6  0  6 15 12]
 [11 10  1  7 19  2 19  0]]

Row 2 of rank 1 is:  [18 19 14  3 19  0 14 16]
Row 2 of rank 2 is:  [[18 19 14  3 19  0 14 16]]
Row 2 of rank 2 (another method) is: [[18 19 14  3 19  0 14 16]]


In [185]:
a = np.array([ [1,2],[3,4],[5,6] ])
b = np.array([ [0,1,2],[0,1,0] ])
print_np(a)
print('')
print_np(b)
print('')
#Indexing array a and b 
c = np.array([ a[0,0], a[1,1], b[0,2] ])                 #Rank 1 array after indexing both rank 2 a & b arrays
d = np.array([ [ a[0,1], b[0,2]], [b[1,1], a[2,1] ] ]) #Rank 2 array after indexing both rank 2 a & b arrays
print_np(c)
print('')
print_np(d)

Type is <class 'numpy.ndarray'>
Shape is  (3, 2)
Values are: 
[[1 2]
 [3 4]
 [5 6]]

Type is <class 'numpy.ndarray'>
Shape is  (2, 3)
Values are: 
[[0 1 2]
 [0 1 0]]

Type is <class 'numpy.ndarray'>
Shape is  (3,)
Values are: 
[1 4 2]

Type is <class 'numpy.ndarray'>
Shape is  (2, 2)
Values are: 
[[2 2]
 [1 6]]


## Array maths

In [193]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#Elementwise sum; both produce the array
print(x+y)
print(np.add(x,y), '\n')
#Elementwise difference; both produce the array
print(x-y)
print(np.subtract(x,y), '\n')
#Elementwise product; both produce the array
print(x*y)
print(np.multiply(x,y), '\n')
#Elementwise division; both produce the array
print(x/y)
print(np.divide(x,y), '\n')
#Elementwise square root; produce the array
print(np.sqrt(x), '\n')
#Matmul
print(np.matmul(x,y))
print(np.dot(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [202]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

print_np(x)
print_np(y)
print_np(v)
print_np(w)

print('')
#Inner product of vectors; both produce 219 (dot product)
print(v.dot(w))
print(np.dot(v,w)) # v * w'

#Matrix/Vector product; both produce the rank 1 array
#np.dot() and np.matmul() have the same function
print(x.dot(v))
print(np.dot(x,v))
print(np.matmul(x,v))

#Matrix/Matrix product; both produce the rank 2 array
#np.dot() and np.matmul() have the same function
print(x.dot(y))
print(np.dot(x,y))
print(np.matmul(x,y))

Type is <class 'numpy.ndarray'>
Shape is  (2, 2)
Values are: 
[[1 2]
 [3 4]]
Type is <class 'numpy.ndarray'>
Shape is  (2, 2)
Values are: 
[[5 6]
 [7 8]]
Type is <class 'numpy.ndarray'>
Shape is  (2,)
Values are: 
[ 9 10]
Type is <class 'numpy.ndarray'>
Shape is  (2,)
Values are: 
[11 12]

219
219
[29 67]
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [214]:
print_np(x)
#Transpose matrix
print('Transpose rank 2 matrix: \n%s' % x.T) #Transpose rank 2 matrix
print('')
print_np(v)
print('Transpose rank 1 matrix: \n%s' % v.T) #Transpose rank 1 matrix

Type is <class 'numpy.ndarray'>
Shape is  (2, 2)
Values are: 
[[1 2]
 [3 4]]
Transpose rank 2 matrix: 
[[1 3]
 [2 4]]

Type is <class 'numpy.ndarray'>
Shape is  (2,)
Values are: 
[ 9 10]
Transpose rank 1 matrix: 
[ 9 10]


In [222]:
x = np.array([[1,2],[3,4],[5,6]])
print_np(x)
print('')
print(np.sum(x))                                           #Compute sum of all element
print('Sum of each column(axis=0): ', np.sum(x, axis=0))   #Compute sum of each column
print('Sum of each row(axis=1): ', np.sum(x, axis=1))      #Compute sum of each row

Type is <class 'numpy.ndarray'>
Shape is  (3, 2)
Values are: 
[[1 2]
 [3 4]
 [5 6]]

21
Sum of each column(axis=0):  [ 9 12]
Sum of each row(axis=1):  [ 3  7 11]


In [224]:
print (x, '\n')
print (x.T)

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]]


In [225]:
x = np.array([1,2,3]) #Rank 1 array
print (x, '\n')
print (x.T)

[1 2 3] 

[1 2 3]


In [226]:
x = np.array([[1,2,3]]) #Rank 2 array
print (x, '\n')
print (x.T)

[[1 2 3]] 

[[1]
 [2]
 [3]]


## Other useful operations

In [230]:
#We will add the vector v to each row of the matrix x
#storing th result in the matrix y
x = np.array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ]) #Rank 2 array
v = np.array([1,0,1])
y = np.empty_like(x)    #Create an empty matrix with the same shape as x

print_np(x)
print_np(v)
print_np(y)

Type is <class 'numpy.ndarray'>
Shape is  (4, 3)
Values are: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Type is <class 'numpy.ndarray'>
Shape is  (3,)
Values are: 
[1 0 1]
Type is <class 'numpy.ndarray'>
Shape is  (4, 3)
Values are: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [231]:
#Add the vector v to each row of the matrix x
#with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v    #BROADCASTING by FOR loop
print_np(y)

Type is <class 'numpy.ndarray'>
Shape is  (4, 3)
Values are: 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [237]:
vv = np.tile(A=v, reps=(4,2)) #Stack 4 copies of v on top of each other
print_np(vv)

Type is <class 'numpy.ndarray'>
Shape is  (4, 6)
Values are: 
[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [238]:
#BROADCASTING
#We will add the vector v to each row of the matrix x, 
#storing the result in the matrix y
x = np.array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ]) #Rank 2 array
v = np.array([1,0,1])
y = x + v            #Add v to each row of x using BROADCASTING

print_np(y)

Type is <class 'numpy.ndarray'>
Shape is  (4, 3)
Values are: 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [244]:
#Add a vector to each columns of matrix 
x = np.array([ [1,2,3],[4,5,6] ]) #Rank 2 array
print((x.T + w).T)
print('')
#Another solution is to reshape w
#to be a row vector of shape(2,1)
print(x)

[[12 13 14]
 [16 17 18]]
